apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - image: adamhert1/compose_mongodb
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      hostname: mongodb
      restartPolicy: Always
