apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    service: booking-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: booking-service
status:
  loadBalancer: {}
