apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
status:
  loadBalancer: {}
