apiVersion: v1
kind: Service
metadata:
  name: web-tier
  labels:
    service: web-tier
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "2998"
    port: 2998
    targetPort: 2998
  selector:
    service: web-tier
status:
  loadBalancer: {}
